spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/moneytou
    username: moneytou_dba
    password: moneytou
  jpa:
    database: postgresql
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: moneytou
    out-of-order: true
    check-location: false
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
  application:
    admin:
      jmx-name: org.springframework.boot:type=Admin,name=MoneytouApplication


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  datetime:
    scalars:
      zone-conversion-enabled: true