spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/moneytou
    username: moneytou_dba
    password: moneytou
  jpa:
    database: postgresql

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  datetime:
    scalars:
      zone-conversion-enabled: true